# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("BPNHPP_COV_4", "BPNHPP_COV_FRAT_10", "BPNHPP_ZI_18_01_2023", "BPNHPP_ZI_FRAT_18_01_2023", "BP_SPNHPP_ZI_FRAT_05_11_2022", "BP_SPNHPP_ZI_FRAT_07_03_2023", "BP_SPNHPP_ZI_FRAT_10_02_2022_tau_data", "BP_SPNHPP_ZI_FRAT_23_02_2023", "BP_SPNHPP_ZI_FRAT_ZETA_07_03_2023", "NHPP_COV_4", "NHPP_COV_5", "NHPP_COV_FRAT_10", "NHPP_COV_FRAT_26_03_2023", "NHPP_ZI_03_07_2022", "NHPP_ZI_08_08_2022", "NHPP_ZI_1_08_03_2022", "NHPP_ZI_25_03_2023", "NHPP_ZI_FRAT_04_07_2022", "NHPP_ZI_FRAT_04_07_2022_OMEGA_DATA", "NHPP_ZI_FRAT_06_07_2022", "NHPP_ZI_FRAT_26_01_2023", "NHPP_ZI_FRAT_29_12_2022", "NHPP_ZI_LOGISTCOV_09_03_2022", "NHPP_ZI_LOGISTCOV_23_07_2022", "NHPP_ZI_LOGISTCOV_25_03_2023", "NHPP_ZI_LOGISTCOV_FRAT_31_07_2022", "SPNHPP_COV_FRAT", "SPNHPP_ICAR_COV_FRAT_15_09", "SPNHPP_SPARSE_COV_FRAT", "SPNHPP_ZI_FRAT_05_11_2022", "SPNHPP_ZI_LOGISTCOV_FRAT_23_09_2022", "SPNHPP_ZI_LOGISTCOV_FRAT_EFECT_IN_LOG_12_10_2022", "SPNHPP_ZI_RND_EF_DATA_09_11_2022")

# load each stan module
Rcpp::loadModule("stan_fit4BPNHPP_COV_4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4BPNHPP_COV_FRAT_10_mod", what = TRUE)
Rcpp::loadModule("stan_fit4BPNHPP_ZI_18_01_2023_mod", what = TRUE)
Rcpp::loadModule("stan_fit4BPNHPP_ZI_FRAT_18_01_2023_mod", what = TRUE)
Rcpp::loadModule("stan_fit4BP_SPNHPP_ZI_FRAT_05_11_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4BP_SPNHPP_ZI_FRAT_07_03_2023_mod", what = TRUE)
Rcpp::loadModule("stan_fit4BP_SPNHPP_ZI_FRAT_10_02_2022_tau_data_mod", what = TRUE)
Rcpp::loadModule("stan_fit4BP_SPNHPP_ZI_FRAT_23_02_2023_mod", what = TRUE)
Rcpp::loadModule("stan_fit4BP_SPNHPP_ZI_FRAT_ZETA_07_03_2023_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_COV_4_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_COV_5_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_COV_FRAT_10_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_COV_FRAT_26_03_2023_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_03_07_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_08_08_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_1_08_03_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_25_03_2023_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_FRAT_04_07_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_FRAT_04_07_2022_OMEGA_DATA_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_FRAT_06_07_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_FRAT_26_01_2023_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_FRAT_29_12_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_LOGISTCOV_09_03_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_LOGISTCOV_23_07_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_LOGISTCOV_25_03_2023_mod", what = TRUE)
Rcpp::loadModule("stan_fit4NHPP_ZI_LOGISTCOV_FRAT_31_07_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4SPNHPP_COV_FRAT_mod", what = TRUE)
Rcpp::loadModule("stan_fit4SPNHPP_ICAR_COV_FRAT_15_09_mod", what = TRUE)
Rcpp::loadModule("stan_fit4SPNHPP_SPARSE_COV_FRAT_mod", what = TRUE)
Rcpp::loadModule("stan_fit4SPNHPP_ZI_FRAT_05_11_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4SPNHPP_ZI_LOGISTCOV_FRAT_23_09_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4SPNHPP_ZI_LOGISTCOV_FRAT_EFECT_IN_LOG_12_10_2022_mod", what = TRUE)
Rcpp::loadModule("stan_fit4SPNHPP_ZI_RND_EF_DATA_09_11_2022_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
